[package]
name = "outro_08"
version = "0.1.0"
edition = "2021"

[dependencies]
#lazy_static = "^1"
tokio = { version = "1", features = ["full"] }
actix-web = "^4"
serde = {version = "^1", features = ["derive"]}
serde_json = "^1"
once_cell = "1.19.0"
